import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import ImportBsJS from "@/components/importBsJS";

export const metadata: Metadata = {
  title: "SEI Smart Forms",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="favicon.ico" />
      </head>
      <body className="">
        <ImportBsJS />
        {children}
      </body>
    </html>
  );
}
